name: Openai
on:
  push:
    branches:
      - main
    paths:
      - 'functions/openai/**'
      - '.github/workflows/functions-openai.yml'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.SKEET_GCP_SA_KEY }}

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloud-functions@v1'
        with:
          name: 'skeet-openai'
          runtime: 'nodejs18'
