name: Openai
on:
  push:
    branches:
      - main
    paths:
      - 'functions/openai/**'
      - '.github/workflows/functions-openai.yml'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          service_account: 'skeet-example@skeet-example.iam.gserviceaccount.com'

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloud-functions@v1'
        with:
          name: 'openai'
          runtime: 'nodejs18'
